#!/bin/bash

# Pull all the repositories in FOLDER

FOLDER="$HOME/Documents"

recurse() {
	for i in $1/*; do
		if [[ -d "$i" ]] && [[ "$i" == *_repo ]]; then
			cd $i
			echo "##### $(basename $i) #####"
			git pull
			cd ..
		elif [[ -d "$i" ]]; then
			recurse "$i"
		fi
	done 	
}

recurse $FOLDER



