#!/bin/bash

# This file must have the same name that the AWK file that it calls

CURRENT_DIR=$(dirname ${BASH_SOURCE[0]})
CURRENT_FILENAME=$(basename ${BASH_SOURCE[0]})
ALIASES_FILE=$HOME/.bashrc

awk -f $CURRENT_DIR/$CURRENT_FILENAME.awk $ALIASES_FILE